language: generic 
sudo: required 
services: 
  - docker 

before_install: 
  - docker build -t araqi/react-test -f ./client/Dockerfile.dev ./client 

script: 
  - docker run -e CI=true araqi/react-test npm test 

after_success: 
  - docker build -t araqi/multi-client ./client 
  - docker build -t araqi/multi-nginx ./nginx
  - docker build -t araqi/multi-server ./server
  - docker build -t araqi/multi-worker ./worker 

 
# first we need to login to docker cli 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push images to docker hub
  - docker push araqi/multi-client
  - docker push araqi/multi-nginx
  - docker push araqi/multi-server
  - docker push araqi/multi-worker
#this is the end of travis configuration file .
# docker push to private repos. 